Http:
  Listen: "127.0.0.1:10801"
Network: "testnet"
RemoteBootstrap: "https://glacier-labs.github.io/node-bootstrap/"
Keystore:
  PrivateKey: "ypur-private-key"
TEE:
  IpfsURL: "https://greenfield.onebitdev.com/ipfs/"
